services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: authrix_dev
    pull_policy: never
    container_name: authrix_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - authrix-network
  db:
    image: postgres:16-alpine3.20
    container_name: mydata
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin345
      POSTGRES_DB: authrix
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init/schema/schema.sql:/docker-entrypoint-initdb.d/spmi.sql
    networks:
      - authrix-network

volumes:
  postgres-data:
networks:
  authrix-network:
    driver: bridge
